model_name: "TemporalMaxerArchitecture"
dataset_name: h2o
train_split: ['train']
val_split: ['val']
dataset: {
  json_file: /temp_maxer/paul_dataset/h2odataset/data/action_labels/h2o_action_label.json,
  feat_folder: /temp_maxer/paul_dataset/h2odataset/data/slowfast_frames,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 36,
  input_dim: 2304,
  feat_stride: 2,
  num_frames: 16,
  default_fps: 30,
  trunc_thresh: 0.3,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 2304,
}
model: {
  backbone_type: convPooler,
  backbone_arch: [2, 5], # [#feature projection layers, #downsampling layer]
  regression_range: [[0, 4], [2, 8], [4, 16], [8, 32], [16, 64], [32, 10000]],
  fpn_type: identity,
  fpn_norm: layernorm,
  max_buffer_len_factor: 4.0,
  assigner: {
    iou_weight: 2,
    cls_weight: 1.0,
    center_radius: 1.5,
    keep_percent: 1.0,
    confuse_weight: 0.0
  }
}
opt: {
  learning_rate: 0.0001,
  epochs: 20,
  weight_decay: 0.06,
}
loader: {
  batch_size: 2,
  num_workers: 4,
}
train_cfg: {
  init_loss_norm: 250,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: 'none',
}
test_cfg: {
  pre_nms_topk: 5000,
  max_seg_num: 2000,
  min_score: 0.001,
  nms_sigma : 0.4,
  multiclass_nms: True
}
output_folder: ./ckpt/


